### ISSUE TITLE
version mismatch using docker file

### ISSUE THREAD

**Issue by pberkland** [EclairJS/eclairjs-node#71]
Because the docker file contains the nashorn from maven, it will be the previous version from what is in Node master.  The version check should allow either check for node version < nashhorn version, or better yet allow node version == nashorn version - 1

**Comment by doronrosenberg** [comment]
It would probably be best to just do ```<```, as long as the spark version matches.

**Comment by pantchox** [comment]
so what do we do here? i installed the docker image and try to to the simple example 
from `node --harmony rddtop10.js ./dream.txt ` i get a response of `Error: Wrong version of EclairJS-nashorn detected: undefined`
and 2nd run returns 
`Starting WebSocket: ws://172.17.42.1:8888/api/kernels/d1d7d544-7f4c-4cd6-9312-1d975c342e04
Error: Error: Cannot find module eclairjs/Tuple2 in jar:file:/opt/nashorn/lib/eclairjs.jar!/eclairjs/jvm-npm/jvm-npm.js at line number 176 at column number 6
jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:199)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:199)
org.apache.toree.global.StreamState$.withStreams(StreamState.scala:81)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:197)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:197)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

on the docker image: 
`[I 23:40:57.723 NotebookApp] Kernel started: d1d7d544-7f4c-4cd6-9312-1d975c342e04
Starting Spark Kernel with SPARK_HOME=/usr/local/spark
16/07/16 23:40:58 [INFO] o.a.t.Main$$anon$1 - Kernel version: 0.1.0.dev8-incubating-SNAPSHOT
16/07/16 23:40:58 [INFO] o.a.t.Main$$anon$1 - Scala version: Some(2.10.4)
16/07/16 23:40:58 [INFO] o.a.t.Main$$anon$1 - ZeroMQ (JeroMQ) version: 3.2.2
16/07/16 23:40:58 [INFO] o.a.t.Main$$anon$1 - Initializing internal actor system
16/07/16 23:40:58 [INFO] o.a.t.Main$$anon$1 - Connection Profile: {
  "stdin_port" : 45004,
  "control_port" : 40151,
  "hb_port" : 57030,
  "shell_port" : 39316,
  "iopub_port" : 52724,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : "e8aa0f61-cc61-4ad7-9304-10b9c2a05cc6"
}
16/07/16 23:40:59 [INFO] o.a.t.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
16/07/16 23:41:01 [WARN] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/07/16 23:41:03 [WARN] o.a.t.Main$$anon$1 - No external magics provided to PluginManager!
16/07/16 23:41:05 [INFO] o.a.t.Main$$anon$1 - 13 internal plugins loaded
16/07/16 23:41:05 [INFO] o.a.t.Main$$anon$1 - 0 external plugins loaded
[W 23:41:07.754 NotebookApp] Timeout waiting for kernel_info reply from d1d7d544-7f4c-4cd6-9312-1d975c342e04
16/07/16 23:41:07 [INFO] o.a.t.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
java.lang.NullPointerException
	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:21)
	at $iwC$$iwC$$iwC.<init>(<console>:28)
	at $iwC$$iwC.<init>(<console>:30)
	at $iwC.<init>(<console>:32)
	at <init>(<console>:34)
	at .<init>(<console>:38)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreter.scala:361)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreter.scala:356)
	at org.apache.toree.global.StreamState$.withStreams(StreamState.scala:81)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1.apply(ScalaInterpreter.scala:355)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreter$$anonfun$interpretAddTask$1.apply(ScalaInterpreter.scala:355)
	at org.apache.toree.utils.TaskManager$$anonfun$add$2$$anon$1.run(TaskManager.scala:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

16/07/16 23:41:09 [INFO] o.a.t.Main$$anon$1 - Marking relay as ready for receiving messages
16/07/16 23:41:09 [INFO] o.a.t.k.p.v.r.KernelMessageRelay - Unstashing all messages received!
16/07/16 23:41:09 [INFO] o.a.t.k.p.v.r.KernelMessageRelay - Relay is now fully ready to receive messages!
16/07/16 23:41:09 [INFO] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Setting deployMode to client
16/07/16 23:41:09 [WARN] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Locked to Scala interpreter with SparkIMain until decoupled!
16/07/16 23:41:09 [WARN] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Unable to control initialization of REPL class server!
16/07/16 23:41:09 [INFO] o.a.t.b.l.StandardComponentInitialization$$anon$1 - REPL Class Server Uri: http://172.17.0.1:39499
16/07/16 23:41:09 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
16/07/16 23:41:10 [INFO] Remoting - Starting remoting
16/07/16 23:41:10 [INFO] Remoting - Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@172.17.0.1:35540]
16/07/16 23:41:11 [INFO] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Attempting to create Hive Context
16/07/16 23:41:12 [INFO] D.Persistence - Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
16/07/16 23:41:12 [INFO] D.Persistence - Property datanucleus.cache.level2 unknown - will be ignored
16/07/16 23:41:16 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:16 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:18 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:18 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:20 [WARN] o.a.h.h.m.ObjectStore - Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/07/16 23:41:20 [WARN] o.a.h.h.m.ObjectStore - Failed to get database default, returning NoSuchObjectException
16/07/16 23:41:21 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:22 [INFO] D.Persistence - Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
16/07/16 23:41:22 [INFO] D.Persistence - Property datanucleus.cache.level2 unknown - will be ignored
16/07/16 23:41:24 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:24 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:24 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:24 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:24 [INFO] D.Query - Reading in results for query "org.datanucleus.store.rdbms.query.SQLQuery@0" since the connection used is closing
16/07/16 23:41:25 [INFO] D.Datastore - The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
16/07/16 23:41:25 [INFO] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Connecting to spark.master local[*]
16/07/16 23:41:25 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
16/07/16 23:41:25 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
16/07/16 23:41:26 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
16/07/16 23:41:27 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
16/07/16 23:41:27 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
16/07/16 23:41:27 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
16/07/16 23:41:27 [INFO] o.a.t.Main$$anon$1 - Shutting down kernel
16/07/16 23:41:27 [INFO] o.a.t.Main$$anon$1 - Shutting down Spark Context
16/07/16 23:41:27 [INFO] o.a.t.Main$$anon$1 - Shutting down interpreters
16/07/16 23:41:27 [INFO] o.a.t.Main$$anon$1 - Shutting down actor system
[I 23:41:28.077 NotebookApp] Kernel shutdown: d1d7d544-7f4c-4cd6-9312-1d975c342e04
`

whats going on? thanks!

**Comment by bpburns** [comment]
In your eclairjs-node repository..  git checkout branch-0.5  then try again.  It should work.  We need to update the documentation when using the docker container.

**Comment by bpburns** [comment]
This version check is causing more harm than good right now.  We should just remove it.  When we move to spark 2.0 we may have to revisit.

**Comment by pantchox** [comment]
Thanks that did the trick.
it seems though that when i run scripts the docker image is having a lot of errors some with hadoop and libraries that it didnt found, is this common? 
also few silly questions:
- is there a specific script that runs a shell for that?
- when running the the docker image, the ipythonbook server is just a file server, whats the point?
- how do i use ipython notebooks that are in the docker image vs using in the eclair examples repo (not this one)

thanks!

**Comment by bpburns** [comment]
The point of the docker container is to create a simple way to try out eclairjs.  You can also run the notebook server environment on your own.  See these instructions: 
[https://github.com/EclairJS/eclairjs-node/wiki/Build-and-Package](url)

Not sure what you mean by your second question?  Do you mean why do we use the notebook server from an architecture perspective?

**Comment by doronrosenberg** [comment]
I went ahead and updated the README to note the Docker file only works with the latest release.  In this case we have made api-level changes in master that broke the image (you can get it to work by replacing `spark.Tuple2` in the example file with `spark.Tuple` most likely).

The versioning should probably be an internal api level thing that we increment when we break stuff (like the tuple thing)

**Comment by pantchox** [comment]
@bpburns what i meant in my second question is that i can connect to 0.0.0.0:8888 and i see the iphytonotebook server but i see only a file system look and it doesnt do anything, so whats the use of that.

some real tutorials like videos or simple step by step article will be nice if you can recommand (i watched all presentations so far but its not hands on)

thanks!

**Comment by bpburns** [comment]
@pantchox Our nodejs client code talks to the notebook server.  The nodejs application almost acts like an instance of a notebook.  We are using the notebook server as if it were an RPC broker.

**Comment by doronrosenberg** [comment]
@pantchox The errors you see in the docker are common, spark is quite verbose (which can be usefull), they are really more warnings.

As for step by step, what is missing in the Try It part of the README?  We are in dire need of more docs and knowing what is missing will help.

As for a shell, EclairJS/eclairjs-nashorn offers a pure JavaScript shell if you don't need Node support and that doesn't require the Notebook piece as it works against Spark directly.

**Comment by pantchox** [comment]
Thank you both i will explore eclair in more depth.
